batch_size: 32
behavior_dim: 4
behavior_weight: 0.5
commitment_cost: 0.25
dataset_type: single
device: null
disable_behavior: false
dropout_rate: 0.1
embedding_dim: 64
epochs: 100
eval_interval: 5
gradient_clip: 1.0
learning_rate: 0.0003
min_neurons: 30
num_embeddings: 512
num_hiddens: 128
num_residual_hiddens: 64
num_residual_layers: 3
num_workers: 0
patience: 20
quantizer: improved_vq
save_dir: ./results
session_id: null
stride: 10
window_size: 50
